### ISSUE TITLE
Railway - weryfikacja konta

### ISSUE THREAD

**Issue by mmiklas** [ManuelaBoron/Applicant-Tracking-System-ATS#1]
Prawdopodobnie Railway wymaga dodatkowych danych od użytkownika szczegóły pod linkiem Learn More.

**Comment by ManuelaBoron** [comment]
Niestety chyba moje konto zostało już potraktowane jako niezweryfikowane i nie dam rady wrócić do żadnej wersji darmowej. Jedyna jaka mi się wyświetla to Hobby za $5 miesięcznie.
